Test for `grep` exit codes >1
dasilvacontin/dot-only-hunter pull request #2
Opened 2016-12-22 22:35 UTC by jamiemjennings

Fixes https://github.com/dasilvacontin/dot-only-hunter/issues/1

Changes to test for `grep` exit codes >1 which signal an error running `grep`. The `dot-only-hunter` script should exit with an error code if the grep command fails.

Test case:
(modify script to use argument `--asdf` on the grep command line):
```
➜  bin git:(master) ✗ ./dot-only-hunter
Hunting inside 'test' for tests with `.only`...
grep: unrecognized option `--asdf'
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
Error searching for`.only` in your tests. This system may be incompatible.
```

2016-12-22 23:53 UTC, dasilvacontin commented
Thanks for your PRs! Will take a look tomorrow. :)

2017-01-03 11:52 UTC, dasilvacontin requested changes
Thanks much! ❤️

2017-01-03 11:52 UTC, dasilvacontin commented on bin/dot-only-hunter
> +    exit 1
Maybe `exit 2` to differentiate "grep error" from ".only's were found".

2017-01-03 11:52 UTC, dasilvacontin commented on bin/dot-only-hunter
> +    echo "Error searching for\`.only\` in your tests. This system may be incompatible."
I'd prefer "Unexpected `grep` error. Please report this issue! :)\nhttps://github.com/dasilvacontin/dot-only-hunter/issues/new".

Once we make `-R` gracefully fallback to `-r`, all other `grep` errors are unexpected.

2017-01-10 20:06 UTC, jamiemjennings commented
@dasilvacontin: Your two requested changes have been made, and revised output is included in the PR description. PTAL

2017-01-10 21:42 UTC, dasilvacontin commented
Thanks again!

2017-01-10 21:42 UTC, merged